# Generated by Django 3.2.16 on 2022-11-23 10:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20221115_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
