default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DIRS_TEMPLATES:
    - src/project/templates/
  HOST: ""
  DOMAIN_NAME: "http://127.0.0.1:8000"
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0
  REDIS: "redis://127.0.0.1:6379/1"
  CELERY_BROKER: "redis://127.0.0.1:6379"
  EMAIL_HOST_PASSWORD: ""
  STRIPE_PUBLIC_KEY: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""

development:
  GUNICORN_LOGGING : "debug"
  HOST: "*"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"
  DATABASE_URL: "sqlite:///src/db.sqlite3"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
  DATABASE_URL: "sqlite:///src"


docker:
  HOST: "0.0.0.0"
  DOMAIN_NAME: "http://0.0.0.0:8000"
  MODE_DEBUG: false
  PORT: 8000
  WEB_CONCURRENCY: 2
  DATABASE_URL: "postgresql://postgres:12345678@store-db:5432/store-db"
  GUNICORN_LOGGING : "info"
  SECRET_KEY : "1"
  REDIS: "redis://redis"
  CELERY_BROKER: "redis://redis"


deploy:
  HOST: "swankyaleks-shop.onrender.com"
  DOMAIN_NAME: "https://swankyaleks-shop.onrender.com"
  MODE_DEBUG: false
  PORT: 8000
  WEB_CONCURRENCY: 2
  GUNICORN_LOGGING: "info"
  SECRET_KEY: "1"
  VENV_SYNTHETIC: false