default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
  HOST: ""
  DOMAIN_NAME: "http://127.0.0.1:8000"
  MODE_DEBUG: false
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0
  EMAIL_HOST_PASSWORD: ''
  REDIS: "redis://127.0.0.1:6379/1"
  CELERY_BROKER: "redis://127.0.0.1:6379"
  STRIPE_PUBLIC_KEY: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""

development:
  HOST: "*"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
  DATABASE_URL: "sqlite:///src"


docker:
  HOST: "0.0.0.0"
  DOMAIN_NAME: "http://0.0.0.0:8000"
  MODE_DEBUG: true
  PORT: 8000
  WEB_CONCURRENCY: 2
  DATABASE_URL: "postgresql://postgres:12345678@store-db:5432/store-db"
  GUNICORN_LOGGING : "info"
  SECRET_KEY : "1"
  REDIS: "redis://redis"
  CELERY_BROKER: "redis://redis"